language: r

r:
  - oldrel
  - release
  - devel

before_install:
  - sudo apt-get -y install neovim

install:
  - Rscript -e 'install.packages("devtools", repos = "https://cran.rstudio.com")'
  - Rscript -e 'devtools::install_cran("qwraps2")'
  - Rscript -e 'devtools::install_cran("rmarkdown")'
  - Rscript -e 'devtools::install_cran("nycflights13")'

script:
  - make clean
  - make -B


